# serverless.yml
service: frisbee-admin-wizard

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: ${opt:stage, "development"}

plugins:
  - fullstack-serverless
  - ./public-policy-workaround.js

custom:
  fullstack:
    bucketName: deployed-bucket
    distributionFolder: ../client/dist
    indexDocument: index.html